require('dotenv').config()
const { createApp } = require('../../src/app')

const { requests } = require('../../src/graph')
port = 4001
requests.config(`http://localhost:${port}/graphql`)

const setup = require('../setup')
const teardown = require('../teardown')

const port = (Number(process.env.port) + 3) || console.log("Error, no port specified in .env")
let app

beforeAll( async () => {
    app = await createApp()
    app.start()
})


describe("The application", () => {
    test('was created', () => {
        expect(app.name).toBe('app')
    })
})

/*
describe("The getHolding autogenerated request", () => {

    test('returns a result', async () => {
        
        const response = await requests.getHolding(
            { holdingId: "60decb7ad4c2c861dcc9dd6d" })
        //console.log('response', response)
        expect(response.holding.name).not.toBeUndefined()
        
    })

    test('returns a result when using custom data request', async () => {
        
        const response = await requests.getHolding(
            { holdingId: "60decb7ad4c2c861dcc9dd6d" },
            '{ holding { name ticker } }')
        //console.log('response', response)
        expect(response.holding.name).not.toBeUndefined()
        expect(response.holding.ticker).not.toBeUndefined()
        
    })

})
*/


afterAll( async () => {
    app.stop()
})
